# Generated by Django 6.0.4 on 2026-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
