# Generated by Django 6.0.4 on 2026-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_etudiant_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='specialite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='universite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
