# Generated by Django 6.0.4 on 2026-06-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_universite_specialite_matricule_to_etudiant'),
        ('accounts', '0006_user_preferred_language'),
    ]

    operations = [
    ]
