# Generated by Django 6.0.4 on 2026-06-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260621_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
    ]
