# Generated by Django 6.0.3 on 2026-04-05 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDeStage',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('comp_techniques', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('qualite_travail', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('autonomie', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ponctualite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_globale', models.FloatField(editable=False)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('recommanderait', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Peut-être', 'Peut-être')], max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.entreprise')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.offredestage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'etudiant', 'offre'), name='unique_eval_entreprise_etudiant_offre')],
            },
        ),
    ]
