# Generated by Django 6.0.4 on 2026-05-01 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='evaluationdestage', name='autonomie'),
        migrations.RemoveField(model_name='evaluationdestage', name='communication'),
        migrations.RemoveField(model_name='evaluationdestage', name='comp_techniques'),
        migrations.RemoveField(model_name='evaluationdestage', name='ponctualite'),
        migrations.AddField(
            model_name='evaluationdestage',
            name='adaptabilite',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationdestage',
            name='comportement',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationdestage',
            name='travail_equipe',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
