# Generated by Django 6.0.4 on 2026-05-09 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_etudiant_date_de_naissance_and_more'),
        ('evaluations', '0003_alter_evaluationdestage_adaptabilite_and_more'),
        ('offres', '0002_favori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationdestage',
            name='adaptabilite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='evaluationdestage',
            name='comportement',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='evaluationdestage',
            name='qualite_travail',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='evaluationdestage',
            name='travail_equipe',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='AutoEvaluation',
            fields=[
                ('id_auto_eval', models.AutoField(primary_key=True, serialize=False)),
                ('comportement', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('adaptabilite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('travail_equipe', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('qualite_travail', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_globale', models.FloatField(editable=False)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluations', to='accounts.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluations', to='offres.offredestage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'offre'), name='unique_auto_eval_etudiant_offre')],
            },
        ),
    ]
