# Generated by Django 6.0.3 on 2026-04-05 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportDeStage',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('resume', models.TextField()),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='accounts.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.offredestage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'offre'), name='unique_rapport_etudiant_offre')],
            },
        ),
    ]
