# Generated by Django 6.0.3 on 2026-04-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0002_alter_candidature_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('date_absence', models.DateField()),
                ('motif_signalement', models.TextField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='justifications/')),
                ('statut', models.CharField(choices=[('Signaler', 'Signalée'), ('Justifiée', 'Justifiée'), ('Non_justifiée', 'Non justifiée')], default='Signaler', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='candidatures.candidature')),
            ],
        ),
    ]
