# Generated by Django 6.0.3 on 2026-04-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.AutoField(primary_key=True, serialize=False)),
                ('postule_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En_attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée'), ('Retirée', 'Retirée')], default='En_attente', max_length=20)),
                ('texte_lettre_motivation', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='accounts.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offres.offredestage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'offre'), name='unique_candidature_etudiant_offre')],
            },
        ),
    ]
