# Generated by Django 6.0.3 on 2026-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('En_attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée'), ('Convention_en_cours', 'Convention en cours'), ('Stage_actif', 'Stage actif (En cours)'), ('Terminé', 'Stage terminé'), ('Retirée', 'Retirée')], default='En_attente', max_length=20),
        ),
    ]
