"""
Django settings for internhub_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

from django.db.backends.base.base import BaseDatabaseWrapper
BaseDatabaseWrapper.check_database_version_supported = lambda self: None

# Patch for older MariaDB compatibility with Django 6.0+ (only when using MySQL)
import os as _os
_load_dotenv_path = Path(__file__).resolve().parent.parent / '.env'
if _os.path.exists(_load_dotenv_path):
    from dotenv import dotenv_values as _dv
    _db_engine = _dv(_load_dotenv_path).get('DB_ENGINE', 'django.db.backends.mysql')
else:
    _db_engine = _os.environ.get('DB_ENGINE', 'django.db.backends.mysql')

if 'mysql' in _db_engine:
    from django.db.backends.mysql.features import DatabaseFeatures
    DatabaseFeatures.can_return_rows_from_bulk_insert = False
    DatabaseFeatures.can_return_columns_from_insert = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-internhub-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]
if DEBUG:
    ALLOWED_HOSTS += ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Nécessaire pour BLACKLIST_AFTER_ROTATION et le logout
    'corsheaders',
    'django_filters',
    
    # Local apps
    'accounts',
    'offres',
    'candidatures',
    'conventions',
    'rapports',
    'evaluations',
    'etablissements',
    'notifications',
    'absences',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# In development (DEBUG=True) allow all origins.
# In production set CORS_ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
_cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _cors_origins_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

ROOT_URLCONF = 'internhub_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'internhub_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_engine = os.environ.get('DB_ENGINE', 'django.db.backends.mysql')
_db_cfg = {
    'ENGINE': _db_engine,
    'NAME': os.environ.get('DB_NAME', 'stagepro') if 'sqlite' not in _db_engine else BASE_DIR / os.environ.get('DB_NAME', 'db.sqlite3'),
}
if 'mysql' in _db_engine:
    _db_cfg.update({
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # Réutilise la connexion MySQL entre requêtes au lieu d'en ouvrir une
        # nouvelle à chaque fois (coût de handshake/auth perceptible en local).
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', 60)),
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
    })

DATABASES = {'default': _db_cfg}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------
from django.utils.translation import gettext_lazy as _

USE_I18N = True
USE_TZ   = True

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'

LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'EXCEPTION_HANDLER': 'internhub_backend.exception_handler.custom_exception_handler',

    # ── Throttling (limitation du trafic) ────────────────────────────────
    # Classes appliquées globalement à toutes les vues.
    # Les vues sensibles (login, register) utilisent leurs propres classes
    # via throttle_classes = [LoginRateThrottle].
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',         # Anonymes : 100 req/jour (navigation publique)
        'user': '1000/day',        # Authentifiés : 1000 req/jour
        'login': '5/minute',       # Tentatives de connexion : 5/min par IP
        'register': '10/hour',     # Inscriptions : 10/heure par IP
    },
}



# ─────────────────────────────────────────────────────────────────
# Configuration des jetons JWT (Simple JWT)
# ─────────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    # Durée de vie courte de l'access token : limite la fenêtre d'exploitation
    # si un jeton est volé (XSS, interception réseau, etc.).
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_LIFETIME_MINUTES', 15))),

    # Le refresh token vit plus longtemps : il permet de renouveler l'access
    # token sans redemander le mot de passe pendant toute la durée de la session.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_LIFETIME_DAYS', 7))),

    # À chaque rafraîchissement, un NOUVEAU refresh token est émis (rotation) :
    # cela empêche la réutilisation indéfinie d'un même refresh token volé.
    'ROTATE_REFRESH_TOKENS': True,

    # L'ancien refresh token est blacklisté dès qu'il a été utilisé pour une
    # rotation : un jeton rejoué (ex. copié par un attaquant) est donc rejeté.
    # Nécessite l'app 'rest_framework_simplejwt.token_blacklist' (voir INSTALLED_APPS).
    'BLACKLIST_AFTER_ROTATION': True,

    # Champs personnalisés car notre modèle User utilise 'id_utilisateur' comme clé primaire.
    'USER_ID_FIELD': 'id_utilisateur',
    'USER_ID_CLAIM': 'user_id',
}

# Surcharge locale des migrations de 'token_blacklist' : la migration 0006
# d'origine utilise un RENAME COLUMN incompatible avec MariaDB < 10.5.
# Voir internhub_backend/token_blacklist_migrations/0006_auto_20171017_2113.py.
MIGRATION_MODULES = {
    'token_blacklist': 'internhub_backend.token_blacklist_migrations',
}

AUTH_USER_MODEL = 'accounts.User'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# En dev, le hachage PBKDF2 par défaut (~600k itérations) ajoute plusieurs
# centaines de ms perceptibles à chaque login. On utilise un hasher rapide en
# premier (utilisé pour les nouveaux mots de passe) tout en gardant le hasher
# standard en fallback pour vérifier les mots de passe existants.
if DEBUG:
    PASSWORD_HASHERS = [
        'internhub_backend.dev_hashers.FastPBKDF2Hasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    ]

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'internHub <noreply@internhub.mr>')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# ---------------------------------------------------------------------------
# Celery / Redis Configuration
# ---------------------------------------------------------------------------
# Broker and result backend — override via REDIS_URL in production
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# True in development (DEBUG=True) for synchronous task execution without a broker.
# False in production (DEBUG=False) so tasks are dispatched to Redis/Celery workers.
CELERY_TASK_ALWAYS_EAGER = DEBUG

# Task routing — keep results for 1 hour then discard
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXPIRES = 3600

# Periodic Tasks Schedule (requires celery beat process)
# Start with: celery -A internhub_backend beat --loglevel=info
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'auto-reject-expired-conventions': {
        'task': 'conventions.tasks.auto_reject_expired_conventions',
        'schedule': crontab(hour='*/6'),
    },
    'close-expired-absences': {
        'task': 'absences.tasks.close_expired_absences',
        'schedule': crontab(hour=8, minute=0),  # every day at 08:00
    },
}

