# Generated by Django 6.0.3 on 2026-04-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionDeStage',
            fields=[
                ('id_convention', models.AutoField(primary_key=True, serialize=False)),
                ('url_fichier', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('En_attente_validation', 'En attente de validation'), ('Validée', 'Validée'), ('Refusée', 'Refusée')], default='En_attente_validation', max_length=50)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('signe_par_etudiant_le', models.DateTimeField(blank=True, null=True)),
                ('signe_par_entreprise_le', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('numero_convention', models.CharField(max_length=50, unique=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='candidatures.candidature')),
                ('valide_par_chef_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chefdepartement')),
            ],
        ),
    ]
