# Generated by Django 6.0.3 on 2026-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventiondestage',
            name='fichier_signe',
            field=models.FileField(blank=True, null=True, upload_to='conventions/signees/'),
        ),
    ]
