# Generated by Django 6.0.4 on 2026-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0002_conventiondestage_fichier_signe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventiondestage',
            name='url_fichier',
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='fichier_convention',
            field=models.FileField(blank=True, null=True, upload_to='conventions/templates/'),
        ),
    ]
