# Generated by Django 6.0.3 on 2026-04-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreDeStage',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exigences', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_semaines', models.IntegerField(editable=False, null=True)),
                ('localisation', models.CharField(max_length=255)),
                ('teletravail', models.BooleanField(default=False)),
                ('domaine', models.CharField(max_length=100)),
                ('gratification', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('places_disponibles', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Fermée', 'Fermée'), ('Archivée', 'Archivée')], default='Active', max_length=20)),
                ('publie_le', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='accounts.entreprise')),
            ],
        ),
    ]
