# Generated by Django 6.0.4 on 2026-05-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verification_token'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='accounts.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorise_par', to='offres.offredestage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'offre'), name='unique_favori')],
            },
        ),
    ]
